implemented json-find. cleanup to sec

diff --git a/bin/sec b/bin/sec
--- a/bin/sec
+++ b/bin/sec
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
+# Provides simplified access to a key chain (macos version)
 
 source stdlib.sh
 
 KEYCHAIN="my-key-chain"
 # Return codes:
-KEYCHAIN_LOCKED=36
-KEY_NOT_FOUND=44
+declare -i SUCCESS=0 KEYCHAIN_LOCKED=36 KEY_NOT_FOUND=44
 
 main () {
   if [[ -z "$1" ]]; then
@@ -27,12 +27,21 @@ main () {
   $cmd "$@"
   returnCode="$?"
   case $returnCode in
-  $KEYCHAIN_LOCKED) die "Keychain is locked (code $returnCode). Use '$(basename "$0") unlock' to unlock";;
-  $KEY_NOT_FOUND)   die "Key not found (code $returnCode): '$2'";;
-  0);;
-  *) die "Error (code $returnCode)"
+    0);;
+    "$KEYCHAIN_LOCKED") die "Keychain is locked (code $returnCode). Use '$(basename "$0") unlock' to unlock";;
+    "$KEY_NOT_FOUND")   die "Key not found (code $returnCode): '$2'";;
+    *)                  die "Error (code $returnCode)"
   esac
+}
 
+handle_error() {
+  local -i returnCode=$?
+  case $returnCode in
+  "$SUCCESS")         die "Illegal exit code: $returnCode (not expected to be called on success)";;
+  "$KEYCHAIN_LOCKED") die "Keychain is locked (code $returnCode). Use '$(basename "$0") unlock' to unlock";;
+  "$KEY_NOT_FOUND")   die "Key not found '$*' (code $returnCode)";;
+  *)                  die "Error (code $returnCode)";
+  esac
 }
 
 init_key_chain() {
@@ -68,23 +77,24 @@ set_secret() {
 
 rename_secret() {
   (( $# == 2 )) || print_usage
-  secret="$(get_secret "$1")"
-  set_secret "$2" "$secret" || die "Failed to create new secret '$2'"
-  delete_secret "$1"
+  secret="$(get_secret "$1")" || die "Failed to get secret '$1' (error code $?)"
+  set_secret "$2" "$secret" || die "Failed to create new secret '$2' (error code $?)"
+  local output
+  output="$(delete_secret "$1" 2>&1)" || die "Failed to delete secret '$1' (error code $?)"
 }
 
 delete_secret() {
   if [[ -z "$1" ]]; then
     print_usage
   fi
-  security delete-generic-password -a $USER -s "$1" "$KEYCHAIN"
+  security delete-generic-password -a $USER -s "$1" "$KEYCHAIN" > /dev/null || handle_error "$*"
 }
 
 print_usage() {
   cat << EOF
 Usage:
   sec init                         - initialize keychain
-  sec unlock                       - unlock keychain from remote shell
+  sec unlock                       - unlock keychain (to be used from remote shell)
   sec lock                         - lock keychain
   sec set <name> <value>           - set secret value
   sec get <name>                   - get secret value
